baseURL = "https://www.datasingularity.com/"
languageCode = "en-us"
title = "Data Singularity"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/data-singularity-logo.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/data-singularity-logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "Learn how to make data human again. Download the free whitepaper now."
    meta_og_title = "Data Singularity Landing Page"
    meta_og_type = "website"
    meta_og_url = "https://datasingularity.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Agile Information Management with Data Singularity."
    meta_twitter_card = "summary"
    meta_twitter_site = "@tomrijntjes"
    meta_twitter_creator = "@tomrijntjes"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
